---

# fly --target jm login --concourse-url http://localhost:8080
# fly --target jm set-pipeline --config pipeline.yaml --pipeline Walking-Skeleton

resources:

  # GET THE SOURCE CODE

  - name: source-code
    type: git
    icon: github-circle
    # check_every: 5 # Minutes
    source:
      uri: https://github.com/morsley-uk/walking-skeleton
      branch: master
      ignore_paths:
      - .git/**
      - .gitignore
      - License
      - ReadMe.md


jobs:

  - name: compile

    plan:

      - get: source-code
        trigger: true

      # LIST SOURCE CODE

      - task: list
        config:
          inputs:
          - name: source-code
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
          run:
            path: ls
            args: [-laR]

      # CLEAN THE SOURCE CODE

      - task: clean
        config: 
          inputs:
          - name: source-code
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: mcr.microsoft.com/dotnet/core/sdk
              tag: 3.1.101-bionic
          outputs:
          - name: cleaned-code
          run:
            path: sh
            args:
            - -exec
            - |
              cd Pipelines/CI/Scripts
              chmod u+x clean.sh
              cd ../../..
              ./clean.sh 

#  - task: restore

#  - task: build

#  - task: publish