---
resources:

  # GET THE SOURCE CODE

  - name: source-code
    type: git
    icon: github-circle
    # check_every: 5 # Minutes
    source:
      uri: https://github.com/morsley-uk/walking-skeleton
      branch: master

jobs:

  - name: compile-app

    plan:

      - get: source-code
        trigger: true

       # CLEAN THE SOURCE CODE

      - task: clean
        config: 
          inputs:
          - name: source-code
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: mcr.microsoft.com/dotnet/core/sdk
              tag: 3.1.101-bionic
          outputs:
          - name: cleaned-code
          run:
            path: sh # Is it executable?
            args: ["./Scripts/clean.sh"]

#  - task: restore

#  - task: build

#  - task: publish