---

# fly --target lh login --concourse-url http://localhost:8080
# fly --target lh set-pipeline --config pipeline.yaml --pipeline Walking-Skeleton

resources:

  #
  # GET THE SOURCE CODE
  #

  - name: source-master
    type: git
    icon: github-circle
    # check_every: 5 # Minutes
    source:
      uri: https://github.com/morsley-uk/walking-skeleton
      branch: master
      ignore_paths:
      - .git/**
      - .git/*
      - .git/
      - .git
      - .gitignore
      - License
      - ReadMe.md

  #
  # DETERMINE THE SEMANTIC VERSION
  #

  #- name: semantic-version

  #
  # GET THE KUBERNETES CLUSTER 
  #

  #- name: kubernetes-cluster

jobs:

  - name: compile

    plan:

      - get: source-master
        trigger: true

      #
      # LIST SOURCE CODE - MASTER
      #

      - task: tree
        file: source-master/Pipelines/CI/Tasks/tree-source-master.yaml

      #
      # COMPILE THE SOURCE CODE
      #

      - task: build-and-publish
        file: source-master/Pipelines/CI/Tasks/clean-restore-build-publish.yaml

      #
      # LIST PUBLISHED
      #

      - task: tree
        file: published/Pipelines/CI/Tasks/tree-published.yaml

        #
      # CLEAN THE SOURCE CODE
      #

      # - task: clean
      #   file: source-code/Pipelines/CI/Tasks/clean.yaml

      #
      # LIST CLEANED CODE
      #

      # - task: tree
      #   file: cleaned-code/Pipelines/CI/Tasks/tree-cleaned.yaml

      #
      # RESTORE THE DEPENDENCIES
      #

      # - task: restore
      #   file: cleaned-code/Pipelines/CI/Tasks/restore.yaml

      #
      # LIST RESTORERD CODE
      #

      # - task: tree
      #   file: restored-code/Pipelines/CI/Tasks/tree-restored.yaml

      #
      # BUILD THE PROJECT
      #

      # - task: build
      #   file: restored-code/Pipelines/CI/Tasks/build.yaml

#  - task: publish