---

# fly --target lh login --concourse-url http://localhost:8080
# fly --target lh set-pipeline --config pipeline.yaml --pipeline Walking-Skeleton

resources:

  #
  # GET THE SOURCE CODE
  #

  - name: source-master
    type: git
    icon: github-circle
    # check_every: 5 # Minutes
    source:
      uri: https://github.com/morsley-uk/walking-skeleton
      branch: master
      ignore_paths:
      - .git/**
      - .git/*
      - .git/
      - .git
      - .gitignore

  #
  # DETERMINE THE SEMANTIC VERSION
  #

  #- name: semantic-version

  #
  # GET THE KUBERNETES CLUSTER 
  #

  #- name: kubernetes-cluster

jobs:

  - name: ci

    plan:

      - get: source-master
        trigger: true

      #
      # TREE SOURCE CODE - MASTER
      #

      - task: tree-source
        file: source-master/Pipelines/CI/Tasks/tree.yaml
        input_mapping: { folder: source-master }

      #
      #  BUILD THE SOURCE CODE
      #

      - task: build
        file: source-master/Pipelines/CI/Tasks/build.yaml
        input_mapping: { source: source-master }
        output_mapping: { source: source-master }

      #
      # TREE BUILT
      #

      - task: tree-built
        file: source-master/Pipelines/CI/Tasks/tree.yaml
        input_mapping: { folder: source-master }

      #
      # RUN UNIT TESTS
      #

      # - task: unit-tests
      #   file: source-master/Pipelines/CI/Tasks/unit-tests.yaml
      #   input_mapping: { built: source-master }
      #   output_mapping: { built: source-master }

      #
      # TREE UNIT TEST RESULTS
      #

      - task: tree-unit-test-results
        file: source-master/Pipelines/CI/Tasks/tree.yaml
        input_mapping: { folder: source-master }

      #
      #  PUBLISH THE SOURCE CODE
      #

      - task: publish
        file: source-master/Pipelines/CI/Tasks/publish.yaml
        input_mapping: { tested: source-master }
        output_mapping: { tested: source-master }

      #
      # TREE PUBLISHED
      #

      - task: tree-published
        file: source-master/Pipelines/CI/Tasks/tree.yaml
        input_mapping: { folder: source-master }