---

# fly --target lh login --concourse-url http://localhost:8080
# fly --target lh set-pipeline --config pipeline.yaml --pipeline Walking-Skeleton

resources:

  #
  # GET THE SOURCE CODE
  #

  - name: source-master
    type: git
    icon: github-circle
    # check_every: 5 # Minutes
    source:
      uri: https://github.com/morsley-uk/walking-skeleton
      branch: master
      ignore_paths:
      - .git/**
      - .git/*
      - .git/
      - .git
      - .gitignore
      - License
      - ReadMe.md

  #
  # DETERMINE THE SEMANTIC VERSION
  #

  #- name: semantic-version

  #
  # GET THE KUBERNETES CLUSTER 
  #

  #- name: kubernetes-cluster

jobs:

  - name: ci

    plan:

      - get: source-master
        trigger: true

      #
      # LIST SOURCE CODE - MASTER
      #

      - task: tree-source-master
        file: source-master/Pipelines/CI/Tasks/tree-source-master.yaml

      #
      #  BUILD THE SOURCE CODE
      #

      - task: build
        file: source-master/Pipelines/CI/Tasks/build.yaml

      #
      # LIST BUILT
      #

      - task: tree-built
        file: source-master/Pipelines/CI/Tasks/tree-built.yaml

      #
      # RUN UNIT TESTs
      #

      - task: unit tests
        file: source-master/Pipelines/CI/Tasks/unit-tests.yaml

      #
      # LIST UNIT TEST RESULTS
      #

      - task: tree-unit-tested
        file: source-master/Pipelines/CI/Tasks/tree-unit-tested.yaml

      #
      # LIST CLEANED CODE
      #

      # - task: tree
      #   file: cleaned-code/Pipelines/CI/Tasks/tree-cleaned.yaml

      #
      # RESTORE THE DEPENDENCIES
      #

      # - task: restore
      #   file: cleaned-code/Pipelines/CI/Tasks/restore.yaml

      #
      # LIST RESTORERD CODE
      #

      # - task: tree
      #   file: restored-code/Pipelines/CI/Tasks/tree-restored.yaml

      #
      # BUILD THE PROJECT
      #

      # - task: build
      #   file: restored-code/Pipelines/CI/Tasks/build.yaml

#  - task: publish