---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mcr.microsoft.com/dotnet/core/sdk
    tag: 3.1-focal

inputs:
- name: built

outputs:
- name: built
  
run:
  path: sh
  args:
  - -exec
  - |
    chmod u+x built/Pipelines/Scripts/unit-tests.sh
    bash built/Pipelines/Scripts/unit-tests.sh