---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: walking-skeleton-app
  labels:
    app: walking-skeleton-app
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: walking-skeleton-app
  template:
    metadata:
      labels:
        app: walking-skeleton-app
    spec:
      containers:
        - name: walking-skeleton
          image: johnmorsley/walking-skeleton-api
          ports:
            - name: http
              containerPort: 7777