---
apiVersion: v1
kind: Service
metadata:
  name: walking-skeletion-svc
spec:
  type: LoadBalancer
  selector:
    app: walking-skeletion-app
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777  