---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mcr.microsoft.com/dotnet/core/sdk
    tag: 3.1.101-bionic

inputs:
- name: source

outputs:
- name: built

run:
  path: sh
  args:
  - -exec
  - |
    timedatectl set-local-rtc 1
    apt update
    apt upgrade -y
    apt install rsync -y
    chmod u+x source/Pipelines/CI/Scripts/build.sh
    bash source/Pipelines/CI/Scripts/build.sh