---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mcr.microsoft.com/dotnet/core/sdk
    tag: 3.1-bionic

inputs:
- name: source

outputs:
- name: source

run:
  path: sh
  args:
  - -exec
  - |
    chmod u+x source/Pipelines/CI/Scripts/build.sh
    bash source/Pipelines/CI/Scripts/build.sh