---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mcr.microsoft.com/dotnet/core/sdk
#    tag: 3.1.101-alpine
#    tag: 3.1.101-buster
    tag: 3.1.101-bionic

inputs:
- name: source-master

outputs:
- name: source-master
#- name: built

run:
  path: sh
  args:
  - -exec
  - |
#    ls -la
    chmod u+x source-master/Pipelines/CI/Scripts/build.sh
    bash source-master/Pipelines/CI/Scripts/build.sh 
#    cp -r source-master/ built/
#    cp -a source-master/. built/
#    chmod u+x built/Pipelines/CI/Scripts/test.sh
#    bash built/Pipelines/CI/Scripts/test.sh 
#    cp -a built/TestResults/. test-results/