---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mcr.microsoft.com/dotnet/core/sdk
    tag: 3.1.101-bionic

inputs:
- name: source

outputs:
- name: built

run:
  path: sh
  args:
  - -exec
  - |
    chmod u+x source-master/Pipelines/CI/Scripts/build.sh
    bash source-master/Pipelines/CI/Scripts/build.sh