---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mcr.microsoft.com/dotnet/core/sdk
    tag: 3.1.101-bionic

inputs:
- name: restored-code

outputs:
- name: built-code

run:
  path: sh
  args:
  - -exec
  - |
    ls -la
    chmod u+x restored-code/Pipelines/CI/Scripts/build.sh
    bash restored-code/Pipelines/CI/Scripts/build.sh 
    cp -a restored-code/. built-code/