---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mcr.microsoft.com/dotnet/core/sdk
    tag: 3.1.101-bionic

inputs:
- name: source-master

outputs:
- name: published

run:
  path: sh
  args:
  - -exec
  - |
    ls -la
    chmod u+x source-master/Pipelines/CI/Scripts/build-and-publish.sh
    bash source-master/Pipelines/CI/Scripts/build-and-publish.sh 
    cp -a source-master/Published. published/