---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: 18.04

inputs:
- name: tested

outputs:
- name: tested

run:
  path: sh
  args:
  - -exec
  - |
    apt update -y
    apt install apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    apt update -y
    apt install docker-ce -y
    chmod u+x tested/Pipelines/CI/Scripts/containerise.sh
    bash tested/Pipelines/CI/Scripts/containerise.sh