---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: docker
    tag: 19.03

inputs:
- name: tested

outputs:
- name: tested

run:
  path: sh
  args:
  - -exec
  - |
    chmod u+x tested/Pipelines/CI/Scripts/containerise.sh
    bash tested/Pipelines/CI/Scripts/containerise.sh