---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mcr.microsoft.com/dotnet/core/sdk
    tag: 3.1.101-bionic

inputs:
- name: cleaned-code

outputs:
- name: restored-code

run:
  path: sh
  args:
  - -exec
  - |
    ls -la
    chmod u+x cleaned-code/Pipelines/CI/Scripts/clean.sh
    bash cleaned-code/Pipelines/CI/Scripts/clean.sh 
    cp -a cleaned-code/. restored-code/