---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: johnmorsley/alpine-with-utilities
    #tag: 1.0

inputs:
- name: restored-code

run:
  path: sh
  args:
  - -exec
  - |
    tree