---

resources:
  
  #
  # DOCKER
  #
  - name: docker
    type: docker-image
    icon: docker
    source: morsley
      repository: jasonmorsleyio/walking-skeleton-api
      username: ((docker-username))
      password: ((docker-password))
  
  #
  # S3
  #

  #- name: kubeconfig
  #  type: 
    
jobs:
  
  - name: cd
    
    plan:
      
      - get: docker
        trigger: true
        
      - task: get-kubeconfig
        file: master/Pipelines/CD/Tasks/tree.yaml